jobs:
  build:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Build Script
          command: python google_page.py

  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest --maxfail=1 --disable-warnings --html=reports/report.html

workflows:
  run_test_deploy:
    jobs:
      - run_script
      - test:
          requires:
            - run_script
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main

